#pragma once
#define WFI_WM_CLIENT_NOTIFY_HOOK (WM_APP + 1)
#define WFI_WM_HOST_EXEC_SYSCOMMAND (WM_APP + 1)
#define WFI_WM_HOST_CONFIG (WM_APP + 2)
enum WFI_HOST_CONFIG {
	WFI_HOST_CONF_NONE = 0,
	WFI_HOST_CONF_BLOCK_SYSCOMMAND,
	WFI_HOST_CONF_ALLOW_SYSCOMMAND,
	WFI_HOST_CONF_HOOK_SYSCOMMAND,
	WFI_HOST_CONF_UNHOOK_SYSCOMMAND,
	WFI_HOST_CONF_SET_BACKGROUND,
	WFI_HOST_CONF_SET_MIN_WIDTH,
	WFI_HOST_CONF_SET_MIN_HEIGHT,
	WFI_HOST_CONF_SET_MAX_WIDTH,
	WFI_HOST_CONF_SET_MAX_HEIGHT,
};